databases:
  - name: mysite
    databaseName: mysite
    user: mysite
    plan: free

services:
  - type: web
    name: mysite
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "./bin/rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: k6AcsJgx1jyE7dWi79+iuAh9KeMN3KbzlE1xJxKCk0fLmqL4ZLbaVljjiIfJq6Q/p21WVC5rQlK/hRg8M73a5BO60JmUa+/eGoImrXGQThOmKV+n0PRJMQESFV5VisHiPt/w34LTm6wy8eh0LibvKQsgDq400VTeNYZtbGmzDdIe5dMcDcqkVmB4OS7YWnwLQggDYU5luO1i/Wnu7Ktxge57ocLi7heR+ygtmGbZTtVx0Ql/13A2komzU9W57VumneEpao7FAwj4zh47gFqtA/z9m2j5s7R4kxxLJuqEPKwnA830gxaMDpabfIxyOFXOPleq475D7Ivj7g39GwrrObrXYE9HnxTGez0CsHvQzP/vAdeXewaygi1S960C/PnK41yL8qkjqFZubXcGKjabD3OymTRo--8cTKhSuQ53B68Db3--VweupylT7YcWoYGNB3ftcA==
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default